/**
 * Runtime Configuration Service for Portal
 *
 * Loads configuration from the server-generated runtime config file.
 * This avoids hardcoding environment-specific values.
 */

// TODO: Implement full runtime config like CRM has
// For now, this is a stub that will be expanded

import { Injectable, signal } from '@angular/core';

export interface SupabaseConfig {
  url: string;
  anonKey: string;
}

export interface RuntimeConfig {
  supabase: SupabaseConfig;
  environment: 'production' | 'development';
  apiUrl?: string;
  edgeFunctionsBaseUrl?: string;
  supportEmail?: string;
}

@Injectable({ providedIn: 'root' })
export class RuntimeConfigService {
  private config = signal<RuntimeConfig | null>(null);

  constructor() {
    this.loadConfig();
  }

  private loadConfig(): void {
    // Load from window.__RUNTIME_CONFIG__ (generated by server/build)
    const runtimeConfig = (window as any).__RUNTIME_CONFIG__;
    if (runtimeConfig) {
      this.config.set(runtimeConfig);
      return;
    }

    // Fallback: load from environment variables
    const envConfig: RuntimeConfig = {
      supabase: {
        url: (window as any).__ENV__?.['SUPABASE_URL'] || '',
        anonKey: (window as any).__ENV__?.['SUPABASE_ANON_KEY'] || '',
      },
      environment:
        (window as any).__ENV__?.['NODE_ENV'] === 'production' ? 'production' : 'development',
    };

    this.config.set(envConfig);
  }

  get(): RuntimeConfig | null {
    return this.config();
  }

  getSupabase(): SupabaseConfig | null {
    return this.config()?.supabase || null;
  }
}
